baseurl: 
title: Agilogy
subtitle: A blog about code and the people making it
author: Agilogy
simple_search: http://google.com/search
description:
name: agilogy
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /:year-:month-:day-:title:output_ext
timezone: Europe/Madrid
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: master
